export const UI_LABELS = {
  BUTTON: {
    APPROVE: 'Approve',
    APPROVE_ALL: 'Approve All',
    BACK_TO_EDIT: 'Back to Editing',
    CANCEL: 'Cancel',
    CLOSE: 'Close',
    CONFIRM: 'Confirm',
    CONFIRM_DISCARD: 'Discard',
    CONTINUE: 'Continue',
    DEFER: 'Close',
    DELETE: 'Delete',
    DISCARD: 'Discard',
    DISCARD_ALL: 'Discard All',
    LOCK: 'Lock',
    REJECT: 'Reject',
    REJECT_ALL: 'Reject All',
    REJECT_DISCARD: 'Keep',
    SAVE: 'Save',
    STAGE: 'Stage',
    UNLOCK: 'Unlock',
  },
  CONCEPT: {
    ACTION: {
      CANCEL: 'Cancel',
      DEFER: 'Defer',
      DELETE: 'Delete Concept',
      DISCARD: 'Discard',
      EDIT: 'Edit',
      PENDING: 'Pending',
      REJECT: 'Reject',
      REJECT_ALL: 'Reject All',
      SAVE: 'Save',
      STAGED: 'Staged',
    },
    CHANGE_NAME: {
      REASSIGN: 'Reassign Related Data',
      NAME_ONLY: 'Name Only',
    },
  },
}
