import { SELECTED } from '@/lib/constants/selected.js'

const { REALIZATIONS } = SELECTED.SETTINGS
const { CONCEPT, TO_CONCEPT, LINK_NAME, LINK_VALUE } = REALIZATIONS.FILTERS

const DEFAULT_FILTERS = {
  [TO_CONCEPT]: '',
  [LINK_NAME]: '',
  [LINK_VALUE]: '',
}

const EMPTY_FILTERS = {
  [CONCEPT]: '',
  ...DEFAULT_FILTERS,
}

export { DEFAULT_FILTERS, EMPTY_FILTERS }
