import { UI_LABELS } from './ui/labels.js'
import { UI_PROCESSING } from './ui/processing.js'
import { UI_RESETTING } from './ui/resetting.js'
import { UI_TOOLTIP } from './ui/tooltip.js'

export const UI_TEXT = {
  LABELS: UI_LABELS,
  PROCESSING: {
    DELETING: UI_PROCESSING.DELETING,
    LOADING: UI_PROCESSING.LOADING,
    SAVING: UI_PROCESSING.SAVING,
    UPDATING: UI_PROCESSING.UPDATING,
  },
  TOOLTIP: {
    HISTORY: UI_TOOLTIP.HISTORY,
    REFERENCES: UI_TOOLTIP.REFERENCES,
    TEMPLATES: UI_TOOLTIP.TEMPLATES,
    USERS: UI_TOOLTIP.USERS,
  },
  RESETTING: {
    ALIASES: UI_RESETTING.ALIASES,
    AUTHOR: UI_RESETTING.AUTHOR,
    CHILDREN: UI_RESETTING.CHILDREN,
    MEDIA: UI_RESETTING.MEDIA,
    NAME: UI_RESETTING.NAME,
    PARENT: UI_RESETTING.PARENT,
    RANK: UI_RESETTING.RANK,
    REALIZATIONS: UI_RESETTING.REALIZATIONS,
    TEMPLATES: UI_RESETTING.TEMPLATES,
  },
}
